[package]
name = "ledger-ethereum"
version = "0.1.0"
edition = "2021"
authors = ["Trevor Arjeski <tmarjeski@gmail.com>"]
description = "A library to communicate with the Ledger Ethereum app"
license = "MIT"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ledger-transport = "0.10.0"
ledger-zondax-generic = "0.10.0"

thiserror = "1.0.38"

byteorder = "1.4.3"
k256 = { version = "0.12.0", features = ["ecdsa", "arithmetic", "std"], default-features = false }

[dev-dependencies]
anyhow = "1"
hex = "0.4.3"
ledger-transport-speculos = { git = "https://github.com/trevarj/ledger-rs.git", rev = "2ed9280" }
tokio = { version = "1.25.0", features = ["full"] }
